# Generated by Django 2.1.7 on 2019-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190307_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='identifier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
